INSERT into groups VALUES (1, "Guests");
INSERT into groups VALUES (2, "Default Users");
INSERT into groups VALUES (3, "Admins");

INSERT into permissions
(ug_id,who,p_upload,p_modify_after_upload,p_unvote,p_see_hidden,p_random_skip,p_skip,p_select_edit,p_change_perms,p_updateDb,p_sync,p_vote,p_daemon,p_volume,p_download,p_select_vote)
    VALUES (1,'group',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
INSERT into permissions
(ug_id,who,p_upload,p_modify_after_upload,p_unvote,p_see_hidden,p_random_skip,p_skip,p_select_edit,p_change_perms,p_updateDb,p_sync,p_vote,p_daemon,p_volume,p_download,p_select_vote)
    VALUES (2,'group',0,0,1,0,1,0,0,0,0,0,1,0,0,0,0);
INSERT into permissions
(ug_id,who,p_upload,p_modify_after_upload,p_unvote,p_see_hidden,p_random_skip,p_skip,p_select_edit,p_change_perms,p_updateDb,p_sync,p_vote,p_daemon,p_volume,p_download,p_select_vote)
    VALUES (3,'group',1,1,1,1,1,1,1,1,1,1,1,1,1,1,1); 

# the genres...
insert into genre values ('0', 'Blues');
insert into genre values ('1', 'Classic Rock');
insert into genre values ('2', 'Country');
insert into genre values ('3', 'Dance');
insert into genre values ('4', 'Disco');
insert into genre values ('5', 'Funk');
insert into genre values ('6', 'Grunge');
insert into genre values ('7', 'Hip-Hop');
insert into genre values ('8', 'Jazz');
insert into genre values ('9', 'Metal');
insert into genre values ('10', 'New Age');
insert into genre values ('11', 'Oldies');
insert into genre values ('12', 'Other');
insert into genre values ('13', 'Pop');
insert into genre values ('14', 'R&B');
insert into genre values ('15', 'Rap');
insert into genre values ('16', 'Reggae');
insert into genre values ('17', 'Rock');
insert into genre values ('18', 'Techno');
insert into genre values ('19', 'Industrial');
insert into genre values ('20', 'Alternative');
insert into genre values ('21', 'Ska');
insert into genre values ('22', 'Death Metal');
insert into genre values ('23', 'Pranks');
insert into genre values ('24', 'Soundtrack');
insert into genre values ('25', 'Euro-Techno');
insert into genre values ('26', 'Ambient');
insert into genre values ('27', 'Trip-Hop');
insert into genre values ('28', 'Vocal');
insert into genre values ('29', 'Jazz+Funk');
insert into genre values ('30', 'Fusion');
insert into genre values ('31', 'Trance');
insert into genre values ('32', 'Classical');
insert into genre values ('33', 'Instrumental');
insert into genre values ('34', 'Acid');
insert into genre values ('35', 'House');
insert into genre values ('36', 'Game');
insert into genre values ('37', 'Sound Clip');
insert into genre values ('38', 'Gospel');
insert into genre values ('39', 'Noise');
insert into genre values ('40', 'Alternative Rock');
insert into genre values ('41', 'Bass');
insert into genre values ('42', 'Soul');
insert into genre values ('43', 'Punk');
insert into genre values ('44', 'Space');
insert into genre values ('45', 'Meditative');
insert into genre values ('46', 'Instrumental Pop');
insert into genre values ('47', 'Instrumental Rock');
insert into genre values ('48', 'Ethnic');
insert into genre values ('49', 'Gothic');
insert into genre values ('50', 'Darkwave');
insert into genre values ('51', 'Techno-Industrial');
insert into genre values ('52', 'Electronic');
insert into genre values ('53', 'Pop-Folk');
insert into genre values ('54', 'Eurodance');
insert into genre values ('55', 'Dream');
insert into genre values ('56', 'Southern Rock');
insert into genre values ('57', 'Comedy');
insert into genre values ('58', 'Cult');
insert into genre values ('59', 'Gangsta');
insert into genre values ('60', 'Top 40');
insert into genre values ('61', 'Christian Rap');
insert into genre values ('62', 'Pop/Funk');
insert into genre values ('63', 'Jungle');
insert into genre values ('64', 'Native US');
insert into genre values ('65', 'Cabaret');
insert into genre values ('66', 'New Wave');
insert into genre values ('67', 'Psychadelic');
insert into genre values ('68', 'Rave');
insert into genre values ('69', 'Showtunes');
insert into genre values ('70', 'Trailer');
insert into genre values ('71', 'Lo-Fi');
insert into genre values ('72', 'Tribal');
insert into genre values ('73', 'Acid Punk');
insert into genre values ('74', 'Acid Jazz');
insert into genre values ('75', 'Polka');
insert into genre values ('76', 'Retro');
insert into genre values ('77', 'Musical');
insert into genre values ('78', 'Rock & Roll');
insert into genre values ('79', 'Hard Rock');
insert into genre values ('80', 'Folk');
insert into genre values ('81', 'Folk-Rock');
insert into genre values ('82', 'National Folk');
insert into genre values ('83', 'Swing');
insert into genre values ('84', 'Fast Fusion');
insert into genre values ('85', 'Bebob');
insert into genre values ('86', 'Latin');
insert into genre values ('87', 'Revival');
insert into genre values ('88', 'Celtic');
insert into genre values ('89', 'Bluegrass');
insert into genre values ('90', 'Avantgarde');
insert into genre values ('91', 'Gothic Rock');
insert into genre values ('92', 'Progressive Rock');
insert into genre values ('93', 'Psychedelic Rock');
insert into genre values ('94', 'Symphonic Rock');
insert into genre values ('95', 'Slow Rock');
insert into genre values ('96', 'Big Band');
insert into genre values ('97', 'Chorus');
insert into genre values ('98', 'Easy Listening');
insert into genre values ('99', 'Acoustic');
insert into genre values ('100', 'Humour');
insert into genre values ('101', 'Speech');
insert into genre values ('102', 'Chanson');
insert into genre values ('103', 'Opera');
insert into genre values ('104', 'Chamber Music');
insert into genre values ('105', 'Sonata');
insert into genre values ('106', 'Symphony');
insert into genre values ('107', 'Booty Bass');
insert into genre values ('108', 'Primus');
insert into genre values ('109', 'Porn Groove');
insert into genre values ('110', 'Satire');
insert into genre values ('111', 'Slow Jam');
insert into genre values ('112', 'Club');
insert into genre values ('113', 'Tango');
insert into genre values ('114', 'Samba');
insert into genre values ('115', 'Folklore');
insert into genre values ('116', 'Ballad');
insert into genre values ('117', 'Power Ballad');
insert into genre values ('118', 'Rhytmic Soul');
insert into genre values ('119', 'Freestyle');
insert into genre values ('120', 'Duet');
insert into genre values ('121', 'Punk Rock');
insert into genre values ('122', 'Drum Solo');
insert into genre values ('123', 'Acapella');
insert into genre values ('124', 'Euro-House');
insert into genre values ('125', 'Dance Hall');
insert into genre values ('126', 'Goa');
insert into genre values ('127', 'Drum & Bass');
insert into genre values ('128', 'Club-House');
insert into genre values ('129', 'Hardcore');
insert into genre values ('130', 'Terror');
insert into genre values ('131', 'Indie');
insert into genre values ('132', 'BritPop');
insert into genre values ('133', 'Negerpunk');
insert into genre values ('134', 'Polsk Punk');
insert into genre values ('135', 'Beat');
insert into genre values ('136', 'Christian Gangsta Rap');
insert into genre values ('137', 'Heavy Metal');
insert into genre values ('138', 'Black Metal');
insert into genre values ('139', 'Crossover');
insert into genre values ('140', 'Contemporary Christian');
insert into genre values ('141', 'Christian Rock');
insert into genre values ('142', 'Merengue');
insert into genre values ('143', 'Salsa');
insert into genre values ('144', 'Trash Metal');
insert into genre values ('145', 'Anime');
insert into genre values ('146', 'Jpop');
insert into genre values ('147', 'Synthpop');
insert into genre values ('255', 'Unknown');
